# Site settings
title: "Saitama's Punch"
description: >
  This is my personal notes about technical, manga and everything I find
  interest in my life.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "hieuk09.github.io" # the base hostname & protocol for your site

author:
  fullname: Hieu Nguyen
  github: hieuk09
  twitter: sincepast
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
