# Site settings
title: "Saitama's Punch"
author: "Hieu Nguyen"
description: "This is my personal notes about technical, manga and everything I find interesting in my life."
keywords: "Software Engineering, Manga, Technical, Ruby"
biography: "I am a Senior Software Engineer at <a href='www.tinypulse.com'>TINYpulse</a>, Saigon"

baseurl: ""
url: "http://hieuk09.github.io"

twitter_username: sincepast
github_username: hieuk09

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
